language: java
jdk:
  - openjdk17

branches: # -- 1
  only:
    - main

# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

#Travis CI 서버의 Home
cache: # -- 2
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build" # --3

# CI 실행 완료시 메일로 알람.
notifications: # --4
  email:
    recipients:
      - tjsdn22@naver.com
